"""google books columns

Revision ID: 2e8f2cdc0efe
Revises: 5e4fc04a4b1d
Create Date: 2026-06-11 00:14:38.503386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8f2cdc0efe'
down_revision: Union[str, None] = '5e4fc04a4b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('source', sa.String(length=20), server_default=sa.text("'google_books'"), nullable=False))
    op.add_column('books', sa.Column('external_id', sa.String(length=50), server_default='', nullable=False))
    op.alter_column('books', 'external_id', server_default=None)
    op.add_column('books', sa.Column('subtitle', sa.String(length=500), nullable=True))
    op.add_column('books', sa.Column('publisher', sa.String(length=500), nullable=True))
    op.add_column('books', sa.Column('published_date', sa.Date(), nullable=True))
    op.add_column('books', sa.Column('isbn_13', sa.String(length=13), nullable=True))
    op.add_column('books', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('average_rating', sa.Numeric(precision=2, scale=1), nullable=True))
    op.add_column('books', sa.Column('ratings_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(length=8), nullable=True))
    op.add_column('books', sa.Column('categories', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('books', sa.Column('maturity_rating', sa.String(length=20), nullable=True))
    op.add_column('books', sa.Column('info_link', sa.String(length=2048), nullable=True))
    op.add_column('books', sa.Column('preview_link', sa.String(length=2048), nullable=True))
    op.drop_index('ix_books_open_library_id', table_name='books')
    op.create_index(op.f('ix_books_external_id'), 'books', ['external_id'], unique=False)
    op.create_index(op.f('ix_books_isbn_13'), 'books', ['isbn_13'], unique=False)
    op.create_unique_constraint('uq_books_source_external_id', 'books', ['source', 'external_id'])
    op.drop_column('books', 'open_library_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('open_library_id', sa.VARCHAR(length=50), server_default='', autoincrement=False, nullable=False))
    op.alter_column('books', 'open_library_id', server_default=None)
    op.drop_constraint('uq_books_source_external_id', 'books', type_='unique')
    op.drop_index(op.f('ix_books_isbn_13'), table_name='books')
    op.drop_index(op.f('ix_books_external_id'), table_name='books')
    op.create_index('ix_books_open_library_id', 'books', ['open_library_id'], unique=True)
    op.drop_column('books', 'preview_link')
    op.drop_column('books', 'info_link')
    op.drop_column('books', 'maturity_rating')
    op.drop_column('books', 'categories')
    op.drop_column('books', 'language')
    op.drop_column('books', 'ratings_count')
    op.drop_column('books', 'average_rating')
    op.drop_column('books', 'page_count')
    op.drop_column('books', 'isbn_13')
    op.drop_column('books', 'published_date')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'subtitle')
    op.drop_column('books', 'external_id')
    op.drop_column('books', 'source')
    # ### end Alembic commands ###
